[build]
  command = "npm run build"
  publish = ".next/standalone"
  
[build.environment]
  NEXT_PUBLIC_SHOPIFY_CLIENT_ID = "228a29c72bea51c172e7e65085b563a5"
  SHOPIFY_CLIENT_SECRET = "26a94737d6c15fde5107b1a06389c434"
  NEXTAUTH_SECRET = "your-secret-key-random-string"
  NEXTAUTH_URL = "https://avengerhub.netlifyapp.com"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"