name = "SEO Manager"
client_id = "228a29c72bea51c172e7e65085b563a5"
application_url = "http://localhost:3000"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_content,write_content,read_themes,write_themes,read_script_tags,write_script_tags"

[auth]
redirect_urls = [
  "http://localhost:3000/api/auth/callback/shopify",
  "http://localhost:3000/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false